=== MisaelGG11/Guia32_Grupo02/Ejercicios/dtd_exterma/ejercicio-ii-2b.dtd
<!-- Ejercicio ii 2b-->
<!ELEMENT fichero (ficha+)>
<!ELEMENT ficha (nombre, apellido, direccion*, DUI?,pais,fechaNacimiento)>
<!ELEMENT nombre (#PCDATA)>
<!ATTLIST nombre sexo (masculino|femenino) #REQUIRED>
    	<!ATTLIST nombre edad  CDATA  #IMPLIED>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT DUI (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT fechaNacimiento (#PCDATA)>
<!ELEMENT nacionalidad (#PCDATA)>
<!ELEMENT continente (#PCDATA)>

=== MisaelGG11/Guia32_Grupo02/Ejercicios/dtd_exterma/ejercicio-ii-2b-dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ejemplodtd1.xml -->

<?xml-stylesheet type="text/css" href="ejercicio-ii-1b-dtd.css"?>
<!DOCTYPE fichero SYSTEM "ejercicio-ii-2b.dtd">
<fichero>
 <ficha>
  <nombre sexo="femenino" edad="17">Angelina</nombre>
  <apellido>Fernandez</apellido>
  <direccion>c/Ulises, 36</direccion>
  <pais>El Salvador</pais>
  <fechaNacimiento>14/06/1996</fechaNacimiento>
  <peso>180</peso>
  <nacionalidad>Salvadoreña</nacionalidad>
  <continente>Americano</continente>
 </ficha>
</fichero>
