=== MisaelGG11/Guia32_Grupo02/Ejercicios/dtd_exterma/tareas.dtd
<!-- tareas.dtd -->
<!ELEMENT equipos (equipo+, a?)>
	<!ATTLIST equipos universidad CDATA #FIXED "Universidad de El Salvador">
<!ELEMENT equipo (facultad,(gt|gl|gd), actividad, profesor, coordinador, integrante1, integrante2, integrante3, )>
	<!ATTLIST equipo 
		n-grupo CDATA #REQUIRED
		tema CDATA #REQUIRED>
<!ELEMENT facultad (carrera)>
	<!ATTLIST facultad 
		codigo CDATA #REQUIRED
		nombre CDATA #REQUIRED>
<!ELEMENT carrera (materia)>
	<!ATTLIST carrera 
		codigo CDATA #REQUIRED
		nombre CDATA #REQUIRED>
<!ELEMENT materia (#PCDATA)>
	<!ATTLIST materia 
		codigo CDATA #REQUIRED>
<!ELEMENT gt (#PCDATA)>
<!ELEMENT gl (#PCDATA)>
<!ELEMENT gd (#PCDATA)>
<!ELEMENT actividad (#PCDATA)>
	<!ATTLIST actividad 
		porcentaje CDATA #REQUIRED>
<!ELEMENT profesor (#PCDATA)>
<!ELEMENT coordinador (#PCDATA)>
	<!ATTLIST coordinador 
		carnet CDATA #REQUIRED
		sexo (m|f) "m">
<!ELEMENT integrante1 (#PCDATA)>
	<!ATTLIST integrante1 
		carnet CDATA #REQUIRED
		sexo (m|f) "m">
<!ELEMENT integrante2 (#PCDATA)>
	<!ATTLIST integrante2 carnet CDATA #REQUIRED
		sexo (m|f) "m">
<!ELEMENT integrante3 (#PCDATA)>
	<!ATTLIST integrante3 
		carnet CDATA #REQUIRED
		sexo (m|f) "m">


<!ELEMENT a (#PCDATA) >
	<!ATTLIST a  
		href CDATA #IMPLIED
		xmlns CDATA #IMPLIED 
		target (_blank|_self|marco) "_blank">

=== MisaelGG11/Guia32_Grupo02/Ejercicios/dtd_exterma/tareas.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="./css/tarea.css" ?>
<!-- tarea.xml -->
<!DOCTYPE equipos SYSTEM "tareas.dtd">
<equipos universidad="Universidad de El Salvador">
    <equipo n-grupo="01" tema="Creacion de un sitio web dinamico">
        <facultad codigo="FIA" nombre="Facultad de Ingenieria y Arquitectura">
            <carrera codigo="I10515" nombre="Ingeniería en Sistemas informaticos">
                <materia codigo="TPI115">Técnicas de Programación Para Internet</materia>
            </carrera>
        </facultad>
        <gt>07</gt>
        <actividad porcentaje="35%">Proyecto de aplicación</actividad>
        <profesor>Ing. Balmore Ortiz</profesor>
       
        <p>Integrantes: </p>
        <coordinador carnet="GG20031" sexo="m">Misael Antonio Gómez García</coordinador>
        <integrante1 carnet="FM19038" sexo="m">Fabio Ernesto Flores Mendoza</integrante1>
        <integrante2 carnet="GR19001" sexo="m">Emerson Alexander González Rodríguez</integrante2>
        <integrante3 carnet="PN19017" sexo="f">Juana María Peña Nieto</integrante3>
    </equipo>
    <equipo n-grupo="02" tema="Creacion de un sumador/restador utilizando sumadores y multiplicadores">
        <facultad codigo="FIA" nombre="Facultad de Ingenieria y Arquitectura">
            <carrera codigo="I10715" nombre="Ingeniería Electrica">
                <materia codigo="SDU115">Sistema Digitales I</materia>
            </carrera>
        </facultad>
        <gd>02</gd>
        <actividad porcentaje="15%">Tarea de investigacion</actividad>
        <profesor>Ing. Nelson Amilcar</profesor>
        <p>Integrantes:</p>
        <coordinador carnet="GM20037" sexo="m">Yasser Juvenal Gallador Martínez</coordinador>
        <integrante1 carnet="GE19020" sexo="m">Juan Manuel Gutierrez Escobar</integrante1>
        <integrante2 carnet="LM18005" sexo="f">Maria Luiza Lopez Mendoza</integrante2>
        <integrante3 carnet="FG19007" sexo="f">Marcela Tatina Franco Gomez</integrante3>
    </equipo>
    <equipo n-grupo="03" tema="Proyecto de principio de Arquimídes">
        <facultad codigo="FIA" nombre="Facultad de Ingenieria y Arquitectura">
            <carrera codigo="I10415" nombre="Ingeniería Mecánica">
                <materia codigo="FIR215">Física II</materia>
            </carrera>
        </facultad>
        <gl>05</gl>
        <actividad porcentaje="20%">Reporte de proyecto</actividad>
        <profesor>Ing. Mario Martinez</profesor>
        <p>Integrantes: </p>
        <coordinador carnet="ML19039" sexo="m">Jeffry Alexander Mejía López</coordinador>
        <integrante1 carnet="HS19007" sexo="f">Norma Noemi Hernandez Sanchez</integrante1>
        <integrante2 carnet="MJ18018" sexo="f">Daysi Yamileth Matinez Jurado</integrante2>
        <integrante3 carnet="RC20038" sexo="f">Ana Julia Rivera Cortez</integrante3>
    </equipo>
    <a class="boton" xmlns="http://www.w3.org/1999/xhtml" href="../../index.html" target="_self">Regresar</a>
</equipos>
