<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="ejercicio-ii-1a-dtd.css"?>
<!-- ejemplodtd1.xml -->

<!DOCTYPE fichero [
		<!ELEMENT fichero (ficha+)>
		<!ELEMENT ficha (nombre, apellido, direccion*, DUI?, pais, nup?)>
		<!ELEMENT nombre (#PCDATA)>
		<!ATTLIST nombre sexo (masculino|femenino) #REQUIRED>
            	<!ATTLIST nombre edad  CDATA  #IMPLIED>
		<!ELEMENT apellido (#PCDATA)>
		<!ELEMENT direccion (#PCDATA)>
		<!ELEMENT DUI (#PCDATA)>
		<!ELEMENT pais (#PCDATA)>
		<!ELEMENT nup (#PCDATA)>
		]>
<fichero>
 <ficha>
  <nombre sexo="femenino" edad="17">Angelina</nombre>
  <apellido>Fernandez</apellido>
  <direccion>c/Ulises, 36</direccion>
  <DUI>123456789</DUI>
  <pais>El Salvador</pais>
  <nup>0205060408</nup>
	
 </ficha>
	 <a xmlns="http://www.w3.org/1999/xhtml" href="../../index.html" target="_self">Regresar</a>
</fichero>

