<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="ejercicio-ii-1b-dtd.css"?>
<!-- ejemplodtd1.xml -->

<!DOCTYPE fichero [
		<!ELEMENT fichero (ficha+)>
		<!ELEMENT ficha (nombre, apellido, direccion*, DUI?,pais,fechaNacimiento, nit, estadoCivil?)>
		<!ELEMENT nombre (#PCDATA)>
		<!ATTLIST nombre sexo (masculino|femenino) #REQUIRED>
            	<!ATTLIST nombre edad  CDATA  #IMPLIED>
		<!ELEMENT apellido (#PCDATA)>
		<!ELEMENT direccion (#PCDATA)>
		<!ELEMENT DUI (#PCDATA)>
		<!ELEMENT pais (#PCDATA)>
		<!ELEMENT fechaNacimiento (#PCDATA)>
		<!ELEMENT nit (#PCDATA)>
		<!ELEMENT estadoCivil (#PCDATA)>
		]>
<fichero>
 <ficha>
  <nombre sexo="femenino" edad="17">Angelina</nombre>
  <apellido>Fernandez</apellido>
  <direccion>c/Ulises, 36</direccion>
  <pais>El Salvador</pais>
  <fechaNacimiento>14/06/1996</fechaNacimiento>
  <nit>0621-000600-121-8</nit>
  <estadoCivil>Soltera</estadoCivil>
 </ficha>
	<a xmlns="http://www.w3.org/1999/xhtml" href="../../index.html" target="_self">Regresar</a>
</fichero>
